# https://github.com/fly-toribird/TBFLib/blob/master/.github/workflows/python-publish.yml
name: Upload Python Package

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: ${{ secrets.PYPI_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          pip install setuptools wheel twine
      - name: Build and publish
        run: |
          python -m build
          twine upload dist/*
