# https://github.com/fly-toribird/TBFLib/blob/master/.github/workflows/python-publish.yml
name: Upload Python Package

on: [release]
jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: ${{ secrets.PYPI_TOKEN }}
    steps:
      # retrieve your distributions here

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
